version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/code
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: APIMenu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
    volumes:
      - ./pgdata:/var/lib/postgresql/data
